function a(b,c) {
  try {
    do_something_crazy()
  } catch (npe) {
    rescue()
  } finally {
    recover()
  }
}
